[tools]
tinytex = "latest"

[tasks.install]
description = "Install minimum packages"
run = """
#!/bin/bash
tlmgr install glossaries
tlmgr install glossaries-extra
tlmgr install txfonts helvetic times tex-gyre
"""
alias = "i"

[tasks.build]
description = "Build the project"
run = "latexmk -cd -pdf templateV6.1.tex"
alias = "b"

[tasks.clean]
description = "Clean up after compiling PDF"
run = "latexmk -c"
depends = ["build"]
