[tools]
tinytex = "latest"

[tasks.build]
description = "Build the project"
run = "latexmk -cd -pdf agujournaltemplate.tex"
alias = "b"

[tasks.clean]
description = "Clean up after compiling PDF"
run = "latexmk -c"
depends = ["build"]

[tasks.tectonic]
description = "Build the JGR template with Tectonic"
run = "tectonic ./agujournaltemplate.tex"
